---
seed: 42
data_path: /home/galina/PythonData/kaggle_melanoma
sync_bn: True
num_folds: 5
fold_id: 0
num_workers: 12
experiment_name: "2020-07-09"

model:
  type: timm.create_model
  model_name: efficientnet_b3
  num_classes: 1
  pretrained: True

trainer:
  type: pytorch_lightning.Trainer
  early_stop_callback: False
  default_save_path: ./
  gpus: 1
  use_amp: True
  amp_level: O1
  max_epochs: 100
  distributed_backend: ddp
  num_sanity_val_steps: 2
  train_percent_check: 1
  val_percent_check: 1.0
  progress_bar_refresh_rate: 1
  benchmark: True
  precision: 16

scheduler:
  type: kaggle_melanoma.schedulers.PolyLR
  max_iter: 100

train_parameters:
  batch_size: 24
  stratified: True

checkpoint_callback:
  type: pytorch_lightning.callbacks.ModelCheckpoint
  filepath: "2020-07-09"
  monitor: val_loss
  verbose: True
  mode: min
  save_top_k: -1

val_parameters:
  batch_size: 48

test_parameters:
  batch_size: 12
  tta: d4

optimizer:
  type: torch.optim.SGD
  lr: 0.001
  weight_decay: 0.0001

loss:
  type: torch.nn.BCEWithLogitsLoss

train_aug:
  transform:
    __class_fullname__: albumentations.core.composition.Compose
    bbox_params: null
    keypoint_params: null
    p: 1
    transforms:
      - __class_fullname__: albumentations.augmentations.transforms.SmallestMaxSize
        always_apply: false
        p: 1
        max_size: 256
      - __class_fullname__: albumentations.augmentations.transforms.RandomCrop
        always_apply: false
        p: 1
        height: 256
        width: 256
#      - __class_fullname__: albumentations.augmentations.transforms.RandomRotate90
#        always_apply: false
#        p: 1
      - __class_fullname__: albumentations.augmentations.transforms.Normalize
        always_apply: false
        max_pixel_value: 255.0
        mean:
          - 0.485
          - 0.456
          - 0.406
        p: 1
        std:
          - 0.229
          - 0.224
          - 0.225

val_aug:
  transform:
    __class_fullname__: albumentations.core.composition.Compose
    bbox_params: null
    keypoint_params: null
    p: 1
    transforms:
      - __class_fullname__: albumentations.augmentations.transforms.SmallestMaxSize
        always_apply: false
        p: 1
        max_size: 256
      - __class_fullname__: albumentations.augmentations.transforms.CenterCrop
        always_apply: false
        p: 1
        height: 256
        width: 256
      - __class_fullname__: albumentations.augmentations.transforms.Normalize
        always_apply: false
        max_pixel_value: 255.0
        mean:
          - 0.485
          - 0.456
          - 0.406
        p: 1
        std:
          - 0.229
          - 0.224
          - 0.225

test_aug:
  transform:
    __class_fullname__: albumentations.core.composition.Compose
    bbox_params: null
    keypoint_params: null
    p: 1
    transforms:
      - __class_fullname__: albumentations.augmentations.transforms.SmallestMaxSize
        always_apply: false
        p: 1
        max_size: 256
      - __class_fullname__: albumentations.augmentations.transforms.CenterCrop
        always_apply: false
        p: 1
        height: 256
        width: 256
      - __class_fullname__: albumentations.augmentations.transforms.Normalize
        always_apply: false
        max_pixel_value: 255.0
        mean:
          - 0.485
          - 0.456
          - 0.406
        p: 1
        std:
          - 0.229
          - 0.224
          - 0.225
